image:
  repository: ghcr.io/tfsync/tfsync
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

leaderElection: true

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi

installCRDs: true

serviceAccount:
  controller: tfsync-controller
  runner: tfsync-runner
